config/routes.rb
Rails.application.routes.draw do


  rutarel = ENV.fetch('RUTA_RELATIVA', 'sivel2/')
 

    devise_scope :usuario do
      get 'sign_out' => 'devise/sessions#destroy'
      get 'salir' => 'devise/sessions#destroy',
        as: :terminar_sesion

      post 'usuarios/iniciar_sesion', to: 'devise/sessions#create'
      get 'usuarios/iniciar_sesion', to: 'devise/sessions#new',
        as: :iniciar_sesion

      # El siguiente para superar mala generación del action en el formulario
      # cuando se monta en sitio diferente a / y se autentica mal (genera 
      # /puntomontaje/puntomontaje/usuarios/sign_in )
      if (Rails.configuration.relative_url_root != '/') 
        ruta = File.join(Rails.configuration.relative_url_root, 
                         'usuarios/sign_in')
        post ruta, to: 'devise/sessions#create'
        get  ruta, to: 'devise/sessions#new'
      end
    end

    devise_for :usuarios, :skip => [:registrations], module: :devise
    as :usuario do
      get 'usuarios/edit' => 'devise/registrations#edit', 
        :as => 'editar_registro_usuario'    
      put 'usuarios/:id' => 'devise/registrations#update', 
        :as => 'registro_usuario'            
    end
    resources :usuarios, path_names: { new: 'nuevo', edit: 'edita' } 

    get '/casos/mapaosm' => 'sivel2_gen/casos#mapaosm'

    get '/maps/WORLD' => 'mapatiempo#worldjson', 
             :as => 'worldjson'
    get '/maps/gadm36_COL_1' => 'mapatiempo#colombia', 
             :as => 'colombia'
    get '/casos/mapatiempo' => 'mapatiempo#mapatiempo', 
             :as => 'mapatiempo'
    get '/casos/mapatiempo/datoscovid' => 'mapatiempo#datoscovid', 
             :as => 'mapatiempocovid'

    root 'sivel2_gen/hogar#index'
 # scope

  mount Msip::Engine, at: "/", as: 'msip'
  mount Mr519Gen::Engine, at: "/", as: 'mr519_gen'
  mount Heb412Gen::Engine, at: "/", as: 'heb412_gen'
  mount Sivel2Gen::Engine, at: "/", as: 'sivel2_gen'
  mount Apo214::Engine, at: "/", as: 'apo214'

end

app/models/ability.rb
class Ability  < Apo214::Ability


  GRUPO_DESAPARICION_CASOS = 25


  def tablasbasicas
    r = (Msip::Ability::BASICAS_PROPIAS - 
         [['Msip', 'oficina']]
        ) + Sivel2Gen::Ability::BASICAS_PROPIAS - [
          ['Sivel2Gen', 'actividadoficio'],
          ['Sivel2Gen', 'escolaridad'],
          ['Sivel2Gen', 'estadocivil'],
          ['Sivel2Gen', 'maternidad']
        ] + Apo214::Ability::BASICAS_PROPIAS
    return r
  end

  # Establece autorizaciones con CanCanCan
  def initialize(usuario = nil)
    initialize_sivel2_gen(usuario)
    initialize_apo214(usuario)
    can :contar, Sivel2Gen::Caso
    if usuario && usuario.rol then
      can [:read, :update], Mr519Gen::Encuestausuario
      if Rails.configuration.x.sivel2_desaparicion && 
        usuario && usuario.grupo.pluck(:id).include?(
          GRUPO_DESAPARICION_CASOS)
        can :pestanadesaparicion, Sivel2Gen::Caso
        cannot :solocambiaretiquetas, Sivel2Gen::Caso
      end
      case usuario.rol
      when Ability::ROLADMIN
        can :manage, Mr519Gen::Encuestausuario
      end
    end
  end

end

app/models/msip/persona.rb
require 'apo214/concerns/models/persona'

module Msip
  class Persona < ActiveRecord::Base
    include Apo214::Concerns::Models::Persona
  end
end

app/models/sivel2_gen/caso.rb
require 'sivel2_gen/concerns/models/caso'

module Sivel2Gen 
  class Caso < ActiveRecord::Base
    include Sivel2Gen::Concerns::Models::Caso

    has_many :victima,  foreign_key: "caso_id", dependent: :destroy, 
      class_name: 'Sivel2Gen::Victima', validate: true
  end
end

app/models/sivel2_gen/victima.rb
require 'sivel2_gen/concerns/models/victima'

module Sivel2Gen
  class Victima < ActiveRecord::Base
    include Sivel2Gen::Concerns::Models::Victima

    validate :hijos_valido

    def hijos_valido
      if self.hijos && (self.hijos < 0 || self.hijos > 100)
        errors.add(
          :hijos, "El número de hijos debe estar en blanco o "\
          "ser un número entre 0 y 100")
      end
    end

  end
end

app/models/usuario.rb
require 'sivel2_gen/concerns/models/usuario'

class Usuario < ActiveRecord::Base
    include Sivel2Gen::Concerns::Models::Usuario
end

app/controllers/application_controller.rb
class ApplicationController < Msip::ApplicationController
  protect_from_forgery with: :exception

  # No requiere autorización
end

app/controllers/mapatiempo_controller.rb
class MapatiempoController < ApplicationController

  
  # No se autoriza con una centropoblado porque no la hay, debe ser función a función
  
  def mapatiempo
    authorize! :read, Sivel2Gen::contar
    render :mapatiempo, layout: 'application'
    return
  end

  def datoscovid
    render :file => '/public/data/all.json', 
      :content_type => 'application/json',
      :layout => false
  end

  def worldjson
    render :file => '/public/maps/WORLD.json', 
      :content_type => 'application/json',
      :layout => false
  end

  def colombia
    render :file => '/public/maps/gadm36_COL_1.json', 
      :content_type => 'application/json',
      :layout => false
  end
end

app/controllers/sivel2_gen/casos_controller.rb
# frozen_string_literal: true

require 'sivel2_gen/concerns/controllers/casos_controller'

module Sivel2Gen
  class CasosController < Heb412Gen::ModelosController

    include Sivel2Gen::Concerns::Controllers::CasosController

    before_action :set_caso, only: [:show, :edit, :update, :destroy]
    load_and_authorize_resource class: Sivel2Gen::Caso, 
      except: [:index, :show, :mapaosm, :update]

    include Sivel2Gen::Concerns::Controllers::CasosController

    def campoord_inicial
      'fecha'
    end

  end
end

app/controllers/sivel2_gen/conteos_controller.rb
# encoding: UTF-8

require 'sivel2_gen/concerns/controllers/conteos_controller'

module Sivel2Gen
  class ConteosController < ApplicationController

    include Sivel2Gen::Concerns::Controllers::ConteosController
    load_and_authorize_resource class: Sivel2Gen::Caso
  end
end

app/controllers/turbo/redirection.rb
module Turbo
  module Redirection
    extend ActiveSupport::Concern

    def redirect_to(url = {}, options = {})
      turbo = options.delete(:turbo)

      super.tap do
        if turbo != false && request.xhr? && !request.get?
          visit_location_with_turbo(location, turbo)
        end
      end
    end

    private
      def visit_location_with_turbo(location, action)
        visit_options = {
          action: action.to_s == "advance" ? action : "replace"
        }

        script = []
        script << "Turbo.clearCache()"
        script << "Turbo.visit(#{location.to_json}, #{visit_options.to_json})"

        self.status = 200
        self.response_body = script.join("\n")
        response.content_type = "text/javascript"
        response.headers["X-Xhr-Redirect"] = location
      end
  end
end

app/controllers/usuarios_controller.rb
require 'sivel2_gen/concerns/controllers/usuarios_controller'

class UsuariosController < Heb412Gen::ModelosController

  # autorización en funciones
  
  include Sivel2Gen::Concerns::Controllers::UsuariosController

end

app/helpers/application_helper.rb
module ApplicationHelper
  include Sivel2Gen::ApplicationHelper 
end

app/views/layouts/application.html.erb
<% content_for :titulo do %>
    <%= Msip.titulo %>
<% end %>

<% content_for :menu do %>
  <%= grupo_menus do %>
    <% if !current_usuario.nil? %>
      <%= despliega_abajo "Casos" do %>
        <%= opcion_menu "Listado", sivel2_gen.casos_path,
          desplegable: true %>
        <% if can?(:new, Sivel2Gen::Caso) %>
          <%= opcion_menu "Nuevo Caso", sivel2_gen.new_caso_path,
            desplegable: true %>
          <%= opcion_menu "Refrescar listado de casos", 
            sivel2_gen.casos_refresca_path,
            desplegable: true %>
          <%= opcion_menu "Reporte de validación", sivel2_gen.validarcasos_path,
            desplegable: true %>
          <%= opcion_menu "Reporte de repetidos", sivel2_gen.buscarrepetidos_path,
            desplegable: true %>
          <%= opcion_menu "Víctimas",
            msip.personas_path, desplegable: true %>
          <%= opcion_menu "Importar relatos XRLAT", 
            sivel2_gen.casos_importarrelatos_path, desplegable: true %>
        <% end %>
      <% end %>
      <%= despliega_abajo "Reportes y conteos" do %>
        <%= opcion_menu "Conteo por demografía víctimas", 
          sivel2_gen.conteos_personas_path,
          desplegable: true %>
        <%= opcion_menu "Listado de víctimas y casos", 
          sivel2_gen.victimas_path,
          desplegable: true %>
        <%= opcion_menu "Conteo de victimizaciones individuales", 
          sivel2_gen.conteos_victimizaciones_path,
          desplegable: true %>
        <%= opcion_menu "Conteo general de víctimizaciones", 
          sivel2_gen.conteos_genvic_path,
          desplegable: true %>
        <%= opcion_menu "Gráfica de actos individuales", 
          sivel2_gen.graficar_actos_individuales_path,
          'data-turbo' => false,
          desplegable: true %>
        <%= opcion_menu "Gráfica de victimizaciones individuales", 
          sivel2_gen.graficar_victimizaciones_individuales_path,
          'data-turbo' => false,
          desplegable: true %>
      <% end %>
      <%= despliega_abajo "Mapas" do %>
        <%= opcion_menu "Casos sobre OpenStreetMap", 
          sivel2_gen.casos_mapaosm_path,
          'data-turbo' => false,
          desplegable: true %>
        <%= opcion_menu 'Victimizaciones individuales por departamento', 
          sivel2_gen.mapadepvic_path,
          'data-turbo' => false,
          desplegable: true %>
        <%= opcion_menu "Victimizaciones individuales por municipio", 
          sivel2_gen.mapamunvic_path, 
          'data-turbo' => false,
          desplegable: true %>

      <% end %>
      <% if Rails.configuration.x.sivel2_desaparicion &&
           (can? :pestanadesaparicion, Sivel2Gen::Caso) %>
        <%= despliega_abajo "Desaparición" do %>
          <%= opcion_menu "Lugares preliminares de disposición de cadaveres", 
            apo214.lugarespreliminares_path, desplegable: true %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
  <%= grupo_menus :pull => :right do %>
    <% if !current_usuario.nil? %>
      <%= despliega_abajo "Documentos" do %>
        <%= opcion_menu "Manual", 
          'https://docs.google.com/document/d/1O9UtOC24njbU5UZWmFcsLX96XQ8huELReG5GcTjUKLY/edit?usp=sharing', 
          target: '_blank', desplegable: true %>
        <%= opcion_menu "Nube", heb412_gen.sisini_path,
          desplegable: true %>
        <% if can? :manage, ::Heb412Gen::Plantillahcm %>
          <%= opcion_menu "Plantillas para un listado",
            heb412_gen.plantillashcm_path,
            desplegable: true %>
        <% end %>
        <% if can? :manage, ::Heb412Gen::Plantillahcr %>
          <%= opcion_menu "Plantillas para un registro",
            heb412_gen.plantillashcr_path,
            desplegable: true %>
        <% end %>
      <% end %>
      <%= despliega_abajo "Administrar" do %>
        <%= opcion_menu "Clave y tema del usuario", main_app.editar_registro_usuario_path,
          desplegable: true %>
        <% if session[:capturacaso_acordeon] %>
          <%= opcion_menu 'Desactivar ficha caso vertical', 
            sivel2_gen.fichacasovertical_path,
            desplegable: true, id: 'fichacasovertical' 
          %>
        <% else %>
          <%= opcion_menu 'Activar ficha caso vertical', 
            sivel2_gen.fichacasovertical_path,
            desplegable: true, id: 'fichacasovertical' %>
        <% end %>
        <% if can? :read, Mr519Gen::Encuestausuario %>
          <%= opcion_menu 'Encuestas',
            mr519_gen.encuestasusuario_path,
            desplegable: true %>
        <% end %>
        <% if can? :manage, ::Usuario %>
          <%= opcion_menu "Usuarios", main_app.usuarios_path,
            desplegable: true %>
        <% end %>
        <%= opcion_menu "Árbol de presuntos responsables",
          sivel2_gen.arbol_presponsables_path, desplegable: true %>
        <% if can? :manage, :tablasbasicas %>
          <%= opcion_menu "Tablas básicas", sivel2_gen.tablasbasicas_path,
            desplegable: true %>
        <% end %>
        <% if can? :manage, Msip::Respaldo7z %>
          <%= opcion_menu "Respaldo cifrado", msip.respaldo7z_path,
            desplegable: true %>
        <% end %>
        <% if can? :manage, Mr519Gen::Formulario %>
          <%= opcion_menu "Formularios", mr519_gen.formularios_path,
            desplegable: true %>
        <% end %>
      <% end %>
      <%= opcion_menu "Salir #{current_usuario.nusuario}", 
        main_app.terminar_sesion_path %>
    <% else %>
      <%= opcion_menu "Acerca de", sivel2_gen.acercade_path %>
      <%= opcion_menu "Iniciar sesión", main_app.iniciar_sesion_path %> 
    <% end %>
  <% end %>
<% end %>

<% content_for :piedepagina do %>
  <span style='font-size: 0.8rem; text-align: left'>
    <%= Rails.configuration.x.sivel2_consweb_pie ? 
      Rails.configuration.x.sivel2_consweb_pie.html_safe : '' %>
    <hr>
    <div align="right"> 
      Sistema de información de 
      <a href="https://gitlab.com/pasosdeJesus/sivel2">código abierto</a> 
      desarrollado por 
      <a href="https://www.pasosdeJesus.org" target="_blank">Pasos de Jesús</a>. 
      2024.
    </div>
  </span>
<% end %>

<%= render template: "layouts/msip/application" %>